### PR TITLE
WIP: Tables

### PR DESCRIPTION
**Pull request by akeshavan**
Do not merge, just reporting progress
screen shot 2017-05-18 at 9 39 52 pm

@r03ert0

### CODE REVIEW

**Comment by akeshavan** [comment]
Updating you all on the progress of this! In my sandbox repo, https://github.com/akeshavan/examples/tree/gh-pages/learn_vue (demo : akeshavan.github.io/examples/learn_vue), when you update a coordinate in the table, the sphere on the brain widget automatically moves:
jul 8 2017 11-25 am - edited

You can also rearrange the rows of the table:
jul 8 2017 11-33 am - edited

To implement on the UI:

- table splitting
- row delete
- row add
- mesh descriptors widget (@r03ert0 maybe you could help w/ this??)

**Comment by neelsomani** [comment]
Awesome! Definitely let us know if you need any additional backend functionality, but I think that the existing API should cover everything in the original UI.

**Comment by amanbadhwar** [comment]
Looks exciting. Will have a look @akeshavan. Thanks for adding me to the discussion.

**Comment by akeshavan** [comment]
I'm going to close this for now -- I think version 2.0 will have the new Vue.js-based interface I'm showing here, but for now I think the tables are fine. I can't merge in the Vue part until we are completely separated from server-side templating. Does that sound good @Sharabesh @neelsomani ?

**Comment by neelsomani** [comment]
That makes sense. Sounds good!

**Pull request closed without merging**
