### PR TITLE
Add Python interface for making API requests

### PR DESCRIPTION
**Pull request by neelsomani**

### CODE REVIEW

**Comment by neelsomani** [comment]
Hey @jbpoline, go ahead and take a look at the notebook in `jupyter_notebooks/`. It demonstrates a few API calls. To make a call, just pass in the class name (from `json_api.py` or `github_collections.py`) and a dictionary of arguments, where the arguments are specified at `http://localhost:5000/json/{ENDPOINT_NAME}/help`.

**Comment by jbpoline** [comment]
sounds great - may be for completeness add the loop over the index to get all pmids for a query ("brain must be returning more than 10 :) 
Another thing when retrying, I got "InterfaceError: connection already closed"  : and I had to restart the ipython kernel, is there a timeout on the connection ?

**Comment by Sharabesh** [comment]
I believe that error is thrown by Psycopg2 (the library peewee calls to make the database connection) if the connection is ever dropped. I don't think we ever explicitly defined a timeout.

**Comment by neelsomani** [comment]
Hey, I wasn't able to replicate the error "InterfaceError: connection already closed." If it comes up again, definitely let me know the process that you took, and I'll try to fix it.

I added the loop to get all of the PMIDs for a query, using "vision" as an example.

**Comment by jbpoline** [comment]
Is there a way to keep the connection alive ?

**Comment by jbpoline** [comment]
Thanks for trying to replicate - I'll try again on my side and let you know.  
The addition to the notebook looks great

**Comment by jbpoline** [comment]
here's my "interface" error when trying to run the notebook after the first run has been successul and leaving a bit of time before re-running - any idea?

---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
~/virtualenvs/brainspell/lib/python3.5/site-packages/playhouse/postgres_ext.py in execute_sql(self, sql, params, require_commit, named_cursor)
    371             else:
--> 372                 cursor = self.get_cursor()
    373             try:

~/virtualenvs/brainspell/lib/python3.5/site-packages/playhouse/postgres_ext.py in get_cursor(self, name)
    358             return self.get_conn().cursor(name=name)
--> 359         return self.get_conn().cursor()
    360 

InterfaceError: connection already closed

During handling of the above exception, another exception occurred:

InterfaceError                            Traceback (most recent call last)
<ipython-input-10-6c91e1e71134> in <module>()
      1 first_call = api_call(QueryEndpointHandler, {
----> 2     "q": "brain"
      3 })
      4 
      5 #pp4 = pp(indent=4)

~/code/pasteur/brainspell-neo/brainspell/websockets.py in api_call(func, args)
    116                 "success": 1
    117             }
--> 118             response = func.process(func, response, argsDict["args"])
    119             return response
    120         else:

~/code/pasteur/brainspell-neo/brainspell/json_api.py in process(self, response, args)
     47     def process(self, response, args):
     48         database_dict = {}
---> 49         results = formatted_search(args["q"], args["start"], args["req"])
     50         output_list = []
     51         for article in results:

~/code/pasteur/brainspell-neo/brainspell/search_helpers.py in formatted_search(query, start, param, experiments)
     99         # doing this
    100         return Articles.select(
--> 101             *fields).where(match).limit(numberResults).offset(start).execute()
    102 
    103 

~/virtualenvs/brainspell/lib/python3.5/site-packages/peewee.py in execute(self)
   3147             query_meta = self.get_query_meta()
   3148             ResultWrapper = self._get_result_wrapper()
-> 3149             self._qr = ResultWrapper(model_class, self._execute(), query_meta)
   3150             self._dirty = False
   3151             return self._qr

~/virtualenvs/brainspell/lib/python3.5/site-packages/peewee.py in _execute(self)
   2831     def _execute(self):
   2832         sql, params = self.sql()
-> 2833         return self.database.execute_sql(sql, params, self.require_commit)
   2834 
   2835     def execute(self):

~/virtualenvs/brainspell/lib/python3.5/site-packages/playhouse/postgres_ext.py in execute_sql(self, sql, params, require_commit, named_cursor)
    379             else:
    380                 if require_commit and self.get_autocommit():
--> 381                     self.commit()
    382         return cursor
    383 

~/virtualenvs/brainspell/lib/python3.5/site-packages/peewee.py in __exit__(self, exc_type, exc_value, traceback)
   3512             else:
   3513                 exc_args = exc_value.args
-> 3514             reraise(new_type, new_type(*exc_args), traceback)
   3515 
   3516 class _BaseConnectionLocal(object):

~/virtualenvs/brainspell/lib/python3.5/site-packages/peewee.py in reraise(tp, value, tb)
    132     def reraise(tp, value, tb=None):
    133         if value.__traceback__ is not tb:
--> 134             raise value.with_traceback(tb)
    135         raise value
    136 elif PY2:

~/virtualenvs/brainspell/lib/python3.5/site-packages/playhouse/postgres_ext.py in execute_sql(self, sql, params, require_commit, named_cursor)
    370                 require_commit = False
    371             else:
--> 372                 cursor = self.get_cursor()
    373             try:
    374                 cursor.execute(sql, params or ())

~/virtualenvs/brainspell/lib/python3.5/site-packages/playhouse/postgres_ext.py in get_cursor(self, name)
    357         if name:
    358             return self.get_conn().cursor(name=name)
--> 359         return self.get_conn().cursor()
    360 
    361     def execute_sql(self, sql, params=None, require_commit=True,

InterfaceError: connection already closed

**Comment by jbpoline** [comment]
@neelsomani :  - I am getting confused : on which branch is the "I added the loop to get all of the PMIDs for a query, using "vision" as an example."  commit ?  I thought I saw that but cannot find it anymore

**Comment by neelsomani** [comment]
Hey @jbpoline, it's on master: https://github.com/OpenNeuroLab/brainspell-neo/commit/c904a0de9e2d26e85c13650181cce8f071814775

I tried to replicate the error by waiting for a few minutes before making the API call again, but I still can't seem to replicate it. How long are you waiting between calls?

**Pull request merged**
