### PR TITLE
fix: more tags fit in the modal

### PR DESCRIPTION
**Pull request by akeshavan**
@r03ert0  @jbpoline  @Sharabesh  Did a small style edit to fit more tags:

screen shot 2017-11-13 at 10 14 33 am

### CODE REVIEW

**Comment by akeshavan** [comment]
when your mouse is over a tag, it becomes blue background w/ white text

**Comment by r03ert0** [comment]
Nice!
could the modal use all the screen?
and add sections? (or A, B, C, ... if only alphabetical order exists)

**Comment by neelsomani** [comment]
LGTM. Should I merge?

**Comment by r03ert0** [comment]
<3 !!!

**Pull request merged**
