### PR TITLE
fix: converted bytes to string

### PR DESCRIPTION
**Pull request by akeshavan**
This fixes the herokuapp error -- I think it happened because I'm using python 3.6 and I'm assuming heroku is using 3.5?

### CODE REVIEW

**Comment by Sharabesh** [comment]
When running locally, I am still seeing an error associated with the gh_user["access_token"] call. On running, the page crashes yielding: 

```
  File "brainspell.py", line 502, in get
    gh_user['access_token'])
KeyError: 'access_token'
```

Is the replicable on your computer?

**Comment by akeshavan** [comment]
yes -- try the latest commit?

**Comment by akeshavan** [comment]
nope, that commit broke something else! Don't merge yet!

**Comment by akeshavan** [comment]
ok, this one should work. Let me know! Try adding an article to a collection, and then refresh the page. Make sure it still shows up in the text input, and then try deleting it!

**Comment by Sharabesh** [comment]
Unfortunately it looks like one more error popped up. On running python3 brainspell.py and navigating to the main page I get this error: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "brainspell.py", line 52, in get
    gh_user = self.get_current_github_user()
  File "brainspell.py", line 39, in get_current_github_user
    return json_decode(user_json)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/torngithub.py", line 47, in json_decode
    return json.loads(to_basestring(value))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Last time I just put a Try catch around this method: 
```
    def get_current_github_user(self):
        user_json = self.get_secure_cookie("user")
        if not user_json:
            return {"name": None, "avatar_url": None, "access_token":None}
        else:
            return json_decode(user_json)
```
Just to make sure that it keeps running, but that's probably not the best long term solution. Any ideas?

**Comment by akeshavan** [comment]
Do you know what self.get_secure_cookie("user") is returning? Its something non-empty but not JSON-like. I put in a more specific exception to make debugging easier

**Comment by Sharabesh** [comment]
It looks like get_secure_cookie("user") is defined by: 
```
class GithubLoginHandler(tornado.web.RequestHandler, torngithub.GithubMixin):
       ...
        # if we have a code, we have been authorized so we can log in
        if self.get_argument("code", False):
            user = yield self.get_authenticated_user(
                redirect_uri=redirect_uri,
                client_id=settings["github_client_id"],
                client_secret=settings["github_client_secret"],
                code=self.get_argument("code"))
            if user:
                self.set_secure_cookie("user", json_encode(user))
            else:
                self.clear_cookie("user")
            self.redirect(self.get_argument("next", "/"))
            return
```

But this is only set if a user is already logged in. 
We have to add simplejson to the requirements, but otherwise I think this looks good to pull?

**Pull request merged**
